### ISSUE TITLE
bash: ${bastion_input,,}: bad substitution

### ISSUE THREAD

**Issue by buchmui** [danisla/gcloudfunc#1]
Hello there,

after source'ing the profile:
```
[%n@%M] > source ${HOME}/.bash_profile
[%n@%M] > gcloud-ssh
Instances found:
```
the following error occurs:

``` 
Selection: 13
Use Bastion Host (y/N)? N
bash: ${bastion_input,,}: bad substitution
[%n@%M] >

```

Anyone have a spontaneous idea what it might be?

**Comment by danisla** [comment]
What version of bash are you using? 

Here is mine:

```
bash --version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)
```

**Comment by buchmui** [comment]
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc. 
```

**Comment by buchmui** [comment]
Updated to ``GNU bash, Version 4.4.23(1)-release (x86_64-apple-darwin17.5.0) `` - is working now. Thank you. 

Solution:
```
brew install bash
```

Will update to a current version on mac os x 10.13.6 (17G65) high sierra
